services:

  anonchat-telegram:
    build:
      context: .
    restart: on-failure
    container_name: rabota-poisk-tg
    volumes:
      - .:/app
    working_dir: /app 
    command: /venv/bin/python src/__main__.py